#
### App ###
#
title=Back Stack
version=0.0.0
#
### Database Server ###
#
database.server.path=file:.database/back_stack
database.server.name=back_stack
database.server.address=localhost
database.server.port=9000
#
### Database Client ###
#
database.client.url=jdbc:hsqldb:file:.database/back_stack
database.client.user=sa
database.client.pass=
#
### HTTP Server ###
#
http.server.host=localhost
http.server.port=8080
http.server.backlog=10